//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.AlinanDerslers = new HashSet<AlinanDersler>();
        }
    
        public int ID { get; set; }
        public string LessonID { get; set; }
        public string LessonName { get; set; }
        public string Aciklama { get; set; }
        public int Teacher_SicilNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlinanDersler> AlinanDerslers { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
