//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulProjesi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yoklama
    {
        public int ID { get; set; }
        public string LessonID { get; set; }
        public int Student_Number { get; set; }
        public System.DateTime Date { get; set; }
        public string Geldimi { get; set; }
        public int YoklamaID { get; set; }
    
        public virtual AlinanDersler AlinanDersler { get; set; }
    }
}
